# Generated by Django 5.2 on 2026-04-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoperationlog',
            name='module',
            field=models.CharField(choices=[('users', 'Users'), ('recipes', 'Recipes'), ('community', 'Community'), ('reports', 'Reports'), ('announcements', 'Announcements')], max_length=32),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('mention_post', 'Mention Post'), ('mention_comment', 'Mention Comment'), ('reply_comment', 'Reply Comment'), ('like_post', 'Like Post'), ('like_comment', 'Like Comment'), ('announcement', 'Announcement')], max_length=32),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=255)),
                ('link_path', models.CharField(blank=True, default='', max_length=255)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
