# Generated by Django 5.2 on 2026-04-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_postcomment_parent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=128, unique=True)),
                ('action', models.CharField(choices=[('mask', 'Mask'), ('block', 'Block')], default='mask', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'community_sensitive_word_rule',
                'ordering': ['action', 'word', '-id'],
            },
        ),
    ]
